const QKEY='quoteright_quotes_v2';const CKEY='quoteright_customers_v2';
const get=(k,d=[])=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const money=n=>Number(n).toLocaleString('en-CA',{style:'currency',currency:'CAD'});
const modal=document.getElementById('modal');const form=document.getElementById('quoteForm');
function render(){const qs=get(QKEY),cs=get(CKEY);document.getElementById('quoteCount').textContent=qs.length;document.getElementById('customerCount').textContent=cs.length;document.getElementById('quotedValue').textContent=money(qs.reduce((s,q)=>s+q.total,0));
 const ql=document.getElementById('quoteList');ql.innerHTML=qs.length?qs.slice().reverse().map(q=>`<div class="item"><div><strong>${esc(q.name)}</strong><small>${esc(q.customer||'No customer')} · ${q.date}</small></div><b>${money(q.total)}</b></div>`).join(''):'<div class="empty">No quotes yet. Create your first quote.</div>';
 const cl=document.getElementById('customerList');cl.innerHTML=cs.length?cs.slice().reverse().map(c=>`<div class="item"><div><strong>${esc(c.name)}</strong><small>${esc(c.email||'No email')}</small></div></div>`).join(''):'<div class="empty">No customers yet.</div>';}
function esc(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
document.getElementById('newQuote').onclick=()=>{form.reset();modal.classList.add('open')};document.getElementById('close').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
form.onsubmit=e=>{e.preventDefault();const f=new FormData(form);const materials=+f.get('materials')||0,labour=+f.get('labour')||0,markup=(+f.get('markup')||0)/100,tax=(+f.get('tax')||0)/100;const subtotal=(materials+labour)*(1+markup),total=subtotal*(1+tax);const qs=get(QKEY);qs.push({id:Date.now(),name:f.get('name'),customer:f.get('customer'),total,date:new Date().toLocaleDateString('en-CA')});put(QKEY,qs);const customer=(f.get('customer')||'').trim();if(customer){const cs=get(CKEY);if(!cs.some(c=>c.name.toLowerCase()===customer.toLowerCase())){cs.push({name:customer,email:''});put(CKEY,cs)}}modal.classList.remove('open');render()};
document.getElementById('newCustomer').onclick=()=>{const name=prompt('Customer name');if(!name)return;const email=prompt('Customer email (optional)')||'';const cs=get(CKEY);cs.push({name,email});put(CKEY,cs);render()};document.getElementById('clearQuotes').onclick=()=>{if(confirm('Clear all local demo quotes and customers?')){localStorage.removeItem(QKEY);localStorage.removeItem(CKEY);render()}};document.getElementById('proButton').onclick=()=>alert('Pro waitlist coming next.');render();